require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo-modules-core/scripts/autolinking'

platform :ios, '14.0'

target 'PuraEstate' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    path: config[:react_native_path],
    to_podfile: 'Podfile.lock',
    types: :production,
    hermes_enabled: true
  )

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'PuraEstateTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:react_native_path],
      :mac_catalyst_enabled => false
    )

    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-ObjC']
      end

      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'HERMES_ENABLE_DEBUGGER=1']
        end
      end
    end

    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
