// Re-export everything from the main utils for convenient named imports
export {
  formatCurrency,
  formatNumber,
  formatCompact,
  formatDate,
  formatDateShort,
  formatRelativeTime,
  formatArea,
  formatPricePerSqft,
  getPropertyTypeLabel,
  getListingTypeLabel,
  getStatusColor,
  calculateROI,
  buildSearchUrl,
  parseSearchParams,
  isValidEmail,
  isValidPhone,
  isValidUrl,
  generateId,
  sleep,
  clamp,
  getInitials,
  slugify,
  truncate,
  capitalize,
  titleCase,
  cn,
} from './index';

export type { ROIInput, ROIResult } from './index';
