#!/bin/sh
# Husky 8+ helper script
# This file is auto-generated by Husky

set -e

scriptName=$(basename -- "$0")
hookName=$(sed 's/^_//' <<< "$scriptName")
hookDir=$(dirname -- "$0")
projectDir=$(dirname -- "$(dirname -- "$hookDir")")

export GIT_PARAMS="$*"
export HUSKY_SKIP_HOOKS=0

if ! command -v node >/dev/null 2>&1; then
  exit 0
fi

# Load hook scripts if they exist
if [ -f "$hookDir/$hookName" ]; then
  . "$hookDir/$hookName"
fi
